##
## REFERENCE SNIPPET — bundled with this skill for convenience, NOT a runnable
## module. It omits the provider/variable declarations and the accepted-finding
## (#tfsec:ignore / #checkov:skip) suppressions for readability, so it will not
## `terraform validate` or pass the scanners on its own. The canonical,
## self-contained, lint-clean version lives in the repo at
## iam-user-for-ssm-sessions/terraform-example/ — copy THAT to deploy.
##

##
## Service principal: claude-science-ssm-initiator
##
## A machine identity for "Claude Science", which can only talk to AWS via a
## STATIC IAM access key (no SSO / no role assumption). This user is deliberately
## constrained to a single capability: open an SSM Session Manager session to ONE
## specific EC2 instance, using only the SSH + port-forwarding session documents.
##
## Least-privilege model (see AWS "Sample IAM policies for Session Manager"):
##   * ssm:StartSession authorizes against BOTH the target instance ARN AND the
##     session-document ARN. We allow exactly one instance and exactly three
##     AWS-managed documents (SSH, port-forward local, port-forward remote host).
##   * ssm:SessionDocumentAccessCheck = true is REQUIRED. Without it, holding
##     StartSession implicitly grants the default SSM-SessionManagerRunShell
##     document (a root-capable interactive shell), which would bypass the
##     document allow-list. The condition forces the allow-list to be honored.
##   * Session lifecycle (TerminateSession/ResumeSession) and the ssmmessages
##     data/control channels are scoped to the user's OWN sessions via
##     session/${aws:username}-* . For a non-federated IAM user the SSM session
##     id is "<username>-<random>", so aws:username (NOT aws:userid, which is for
##     federated / assumed-role principals) is the correct policy variable.
##
## The access key is generated by Terraform and stored in Secrets Manager; it is
## never emitted to state output. Rotate by tainting aws_iam_access_key.claude_science_ssm.
##

locals {
  claude_science_ssm_username = "claude-science-ssm-initiator"

  # Target instance: the compchem HPC login node (login.example.internal).
  # This head/login node is ParallelCluster-managed (not created by this repo),
  # so its instance id is pinned here rather than referenced from a resource.
  claude_science_ssm_target_instance_id = "i-0123456789abcdef0"

  # AWS-managed session documents this principal may use. SSH is required for the
  # ssh-over-ssm ProxyCommand; the two port-forwarding documents enable local and
  # remote-host port forwarding respectively.
  claude_science_ssm_allowed_documents = [
    "AWS-StartSSHSession",
    "AWS-StartPortForwardingSession",
    "AWS-StartPortForwardingSessionToRemoteHost",
  ]

  claude_science_ssm_common_tags = {
    Purpose   = "Claude Science SSM session initiator - static IAM key"
    Principal = "claude-science"
    Access    = "ssm-start-session-only"
  }
}

##
## IAM User
##
resource "aws_iam_user" "claude_science_ssm" {
  name = local.claude_science_ssm_username
  path = "/service/"

  tags = merge(local.claude_science_ssm_common_tags, {
    Name = local.claude_science_ssm_username
  })
}

##
## Static access key + Secrets Manager storage
##
resource "aws_iam_access_key" "claude_science_ssm" {
  user = aws_iam_user.claude_science_ssm.name
}

resource "aws_secretsmanager_secret" "claude_science_ssm_key" {
  name        = "service_iam/${local.claude_science_ssm_username}-key"
  description = "Static IAM access key for ${local.claude_science_ssm_username} (SSM start-session only)"

  tags = merge(local.claude_science_ssm_common_tags, {
    Name        = "service_iam/${local.claude_science_ssm_username}-key"
    Description = "Static IAM access key for ${local.claude_science_ssm_username}"
  })
}

# Store both halves of the credential as JSON so the consumer can retrieve the
# full pair from one secret. The secret_string is only ever written to the
# encrypted secret, not surfaced as a Terraform output.
resource "aws_secretsmanager_secret_version" "claude_science_ssm_key" {
  secret_id = aws_secretsmanager_secret.claude_science_ssm_key.id
  secret_string = jsonencode({
    aws_access_key_id     = aws_iam_access_key.claude_science_ssm.id
    aws_secret_access_key = aws_iam_access_key.claude_science_ssm.secret
    region                = var.aws_region
    target_instance_id    = local.claude_science_ssm_target_instance_id
  })
}

##
## Least-privilege SSM start-session policy
##
data "aws_iam_policy_document" "claude_science_ssm_start_session" {

  # (1) Start a session ONLY to the one target instance AND only with the
  #     allow-listed session documents. SessionDocumentAccessCheck forces the
  #     document allow-list to be enforced (blocks the implicit RunShell grant).
  statement {
    sid     = "StartSessionOnTargetInstanceWithAllowedDocuments"
    effect  = "Allow"
    actions = ["ssm:StartSession"]
    resources = concat(
      ["arn:aws:ec2:${var.aws_region}:${data.aws_caller_identity.current.account_id}:instance/${local.claude_science_ssm_target_instance_id}"],
      # AWS-managed session documents (AWS-*) are AWS-owned: their ARN has an
      # EMPTY account-id field (arn:aws:ssm:<region>::document/AWS-...). Pinning
      # our account id here would NOT match the request and StartSession is denied.
      [for doc in local.claude_science_ssm_allowed_documents :
        "arn:aws:ssm:${var.aws_region}::document/${doc}"
      ],
    )
    condition {
      test     = "BoolIfExists"
      variable = "ssm:SessionDocumentAccessCheck"
      values   = ["true"]
    }
  }

  # (2) The SSM messaging channels for the user's OWN sessions. Required for
  #     interactive + port-forwarding data flow. Scoped to this user's sessions.
  statement {
    sid    = "OwnSessionMessageChannels"
    effect = "Allow"
    actions = [
      "ssmmessages:CreateControlChannel",
      "ssmmessages:CreateDataChannel",
      "ssmmessages:OpenControlChannel",
      "ssmmessages:OpenDataChannel",
    ]
    resources = ["arn:aws:ssm:${var.aws_region}:${data.aws_caller_identity.current.account_id}:session/$${aws:username}-*"]
  }

  # (3) Terminate / resume ONLY the user's own sessions.
  statement {
    sid    = "ManageOwnSessions"
    effect = "Allow"
    actions = [
      "ssm:TerminateSession",
      "ssm:ResumeSession",
    ]
    resources = ["arn:aws:ssm:${var.aws_region}:${data.aws_caller_identity.current.account_id}:session/$${aws:username}-*"]
  }
}

resource "aws_iam_policy" "claude_science_ssm_start_session" {
  name        = "${var.account_name}-${var.region_short_name}-policy-claude-science-ssm-start-session"
  path        = "/service/"
  description = "Allow claude-science to start SSM SSH/port-forward sessions to exactly one instance"
  policy      = data.aws_iam_policy_document.claude_science_ssm_start_session.json

  tags = local.claude_science_ssm_common_tags
}

resource "aws_iam_user_policy_attachment" "claude_science_ssm_start_session" {
  user       = aws_iam_user.claude_science_ssm.name
  policy_arn = aws_iam_policy.claude_science_ssm_start_session.arn
}

# Pin the exact set of managed policies on this user: ONLY the SSM start-session
# policy, nothing else. Prevents drift from out-of-band console attachments.
resource "aws_iam_user_policy_attachments_exclusive" "claude_science_ssm" {
  user_name = aws_iam_user.claude_science_ssm.name
  policy_arns = [
    aws_iam_policy.claude_science_ssm_start_session.arn,
  ]
}
